// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class createquestionsandalternatives : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createquestionsandalternatives));
        
        string IMigrationMetadata.Id
        {
            get { return "201504031151185_create questions and alternatives"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
