// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class update_initial_has_many_relationships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_initial_has_many_relationships));
        
        string IMigrationMetadata.Id
        {
            get { return "201504041923505_update_initial_has_many_relationships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
